name: Deploy to Remote Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 45.131.41.112
          username: 81858
          key: zked0babvp
          script: |
            echo "Hello, world!"
