name: Deploy to Remote Server
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 45.131.41.112
          username: root
          password: zked0babvp
          script: |
            docker
            docker images
